---
categories:
- ""
- ""
date: "2017-10-31T22:42:51-05:00"
description: Analysing The Economist's Big Mac Index data.
draft: false
image: burger.jpg
keywords: ""
slug: bigmacindex
title: Big Mac Index
---

<script src="/rmarkdown-libs/kePrint/kePrint.js"></script>
<link href="/rmarkdown-libs/lightable/lightable.css" rel="stylesheet" />


<p>In 1986 <em>The Economist</em> introduced <strong>The Big Mac Index</strong>, providing a unit of comparison for the cost of living in different countries and exchange rates based on the price of a Big Mac burger from McDonald’s. Burgernomics was certainly innovative and in the analysis below I dig into <a href="https://github.com/TheEconomist/big-mac-data">The Economist’s data</a> for insights.</p>
<pre class="r"><code>#importing the raw data from The Economist
source_data &lt;- read_csv(&quot;big-mac-source-data.csv&quot;)
historical_data &lt;- read_csv(&quot;big-mac-historical-source-data.csv&quot;)
bmindex_data &lt;- read_csv(&quot;big-mac-full-index.csv&quot;)</code></pre>
I firstly load and inspect the data from the <code>bmindex_data</code>, which is the data frame I will be drawing my analysis from. It displays information for 56 countries dating back to 2000. The most important variables that the data frame includes are:
<ol>
<ul>
<li><code>local_price</code>: local price for a Big Mac in the local currency</li>
<li><code>dollar_ex</code>: the exchange rate to dollars of the country’s local currency</li>
<li><code>dollar_price</code>: the equivalent dollar price for a Big Mac</li>
</ul>
</ol>
<div id="exchange-rate-mismatch" class="section level1">
<h1>Exchange rate mismatch</h1>
<p>The Big Mac Index, by outlining the differences in local prices (the cost of a Big Mac), suggests what the exchange rate should be and thus reveals any mismatch in exchange rates.</p>
<p>Below I calculate and visualize, for each country, whether the local currency was undervalued or overvalued against the US dollar as of July 2020. To do so I filter and mutate the data frame to calculate for each country the implied exchange rate based on the local price of a Big Mac in US$ and compare it to the actual exchange rate at the time to get the percentage difference.</p>
<pre class="r"><code>#mutating data frame to calculate exchange rate mismatch
er_mismatch &lt;- bmindex_data %&gt;% 
  select(1:7) %&gt;% 
  filter(date == &quot;2020-07-01&quot;) %&gt;% 
  mutate(implied_er = (local_price/5.71)) %&gt;% 
  mutate(mismatch = implied_er-dollar_ex) %&gt;% 
  mutate(percent_miss = (mismatch/dollar_ex)*100)

#visualizing some of the rows to see the output  
er_mismatch %&gt;% 
head(3) %&gt;% 
  #Formatting the table for HTML
kbl(caption = &quot;Exchange Rate Mismatch&quot;) %&gt;% 
  kable_styling() </code></pre>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-1">Table 1: </span>Exchange Rate Mismatch
</caption>
<thead>
<tr>
<th style="text-align:left;">
date
</th>
<th style="text-align:left;">
iso_a3
</th>
<th style="text-align:left;">
currency_code
</th>
<th style="text-align:left;">
name
</th>
<th style="text-align:right;">
local_price
</th>
<th style="text-align:right;">
dollar_ex
</th>
<th style="text-align:right;">
dollar_price
</th>
<th style="text-align:right;">
implied_er
</th>
<th style="text-align:right;">
mismatch
</th>
<th style="text-align:right;">
percent_miss
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
2020-07-01
</td>
<td style="text-align:left;">
ARE
</td>
<td style="text-align:left;">
AED
</td>
<td style="text-align:left;">
United Arab Emirates
</td>
<td style="text-align:right;">
14.75
</td>
<td style="text-align:right;">
3.67
</td>
<td style="text-align:right;">
4.02
</td>
<td style="text-align:right;">
2.58
</td>
<td style="text-align:right;">
-1.090
</td>
<td style="text-align:right;">
-29.7
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-01
</td>
<td style="text-align:left;">
ARG
</td>
<td style="text-align:left;">
ARS
</td>
<td style="text-align:left;">
Argentina
</td>
<td style="text-align:right;">
250.00
</td>
<td style="text-align:right;">
71.24
</td>
<td style="text-align:right;">
3.51
</td>
<td style="text-align:right;">
43.78
</td>
<td style="text-align:right;">
-27.458
</td>
<td style="text-align:right;">
-38.5
</td>
</tr>
<tr>
<td style="text-align:left;">
2020-07-01
</td>
<td style="text-align:left;">
AUS
</td>
<td style="text-align:left;">
AUD
</td>
<td style="text-align:left;">
Australia
</td>
<td style="text-align:right;">
6.55
</td>
<td style="text-align:right;">
1.43
</td>
<td style="text-align:right;">
4.58
</td>
<td style="text-align:right;">
1.15
</td>
<td style="text-align:right;">
-0.284
</td>
<td style="text-align:right;">
-19.8
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>#plotting the under and over valuation of the exchange rates
ggplot(er_mismatch, aes(y = percent_miss, x = name, fill = name, label = currency_code)) +
  geom_col() + 
  labs(title = &quot;Most currencies were undervalued against the Dollar in July 2020&quot;, subtitle = &quot;Percentage difference between the implied and actual exchange rate&quot;, x = &quot;Country&quot;, y = &quot;Percentage mismatch&quot;) + 
  geom_text(color = &quot;white&quot;,size = 1.8, y = -0.8, color = &quot;#C7C8CF&quot;) +
  theme(legend.position = &quot;right&quot;, axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.line = element_line(color = &quot;#C7C8CF&quot;), 
        legend.key = element_rect(fill = &quot;#2B304A&quot;),
        legend.text = element_text(color = &quot;#C7C8CF&quot;),
        legend.title = element_blank(),
         legend.background = element_rect(fill = &quot;#2B304A&quot;))</code></pre>
<p><img src="/blogs/bigmacindex_files/figure-html/plot1-1.png" width="1440" style="display: block; margin: auto;" />
Notably, most currencies were undervalued against the dollar in July 2020, with the exception of the Swiss Franc (CHF), the Lebanese Pound (LBP) and the Swedish Krona (SEK).</p>
</div>
<div id="how-does-the-price-for-a-big-mac-vary-across-countries" class="section level1">
<h1>How does the price for a Big Mac vary across countries?</h1>
<pre class="r"><code>#reducing the data to July 2020 observations only
recent_data &lt;- bmindex_data %&gt;% 
  filter(date == c(&quot;2020-07-01&quot;)) </code></pre>
<pre class="r"><code>favstats(~ dollar_price, data = recent_data)</code></pre>
<pre><code>##   min   Q1 median   Q3  max mean  sd  n missing
##  1.86 2.78    3.5 4.12 6.91 3.58 1.1 56       0</code></pre>
<pre class="r"><code>#plotting the variation in price for a Big Mac as of July 2020
  ggplot(recent_data, aes(x = dollar_price)) +
  geom_vline(xintercept = 3.58, color = &quot;#DA291C&quot;) +
  geom_density(color = &quot;#C7C8CF&quot;) + 
  labs(
    title=&quot;A Big Mac costs $3.58 on average around the world&quot;,
    subtitle=&quot;Distribution of prices for a big Mac as of July 2020&quot;,
    x=&quot;Price(US$)&quot;,
    y=&quot;Density&quot;) +
  theme(panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.text = element_text(color = &quot;#C7C8CF&quot;),
        axis.line = element_line(color = &quot;#C7C8CF&quot;))</code></pre>
<p><img src="/blogs/bigmacindex_files/figure-html/cheapest_burger-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>As of July 2020 a Big Mac was priced, on average $3.58 around the world. Interestingly, the distribution for the price of a Big Mac is right skewed, suggesting that most countries have a relatively cheaper price, also reflected by the box plot below.</p>
<pre class="r"><code>#plotting the variation in price for a Big Mac as of July 2020
  ggplot(recent_data, aes(x = dollar_price)) +
  geom_boxplot(color = &quot;#C7C8CF&quot;) +
  theme_few() +
  labs(
    title=&quot;A Big Mac costs $3.58 on average around the world&quot;,
    subtitle=&quot;Distribution of prices for a big Mac as of July 2020&quot;,
    x=&quot;Price(US$)&quot;,
    y=&quot;Density&quot;) +
  theme(panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.text = element_text(color = &quot;#C7C8CF&quot;),
        axis.line = element_line(color = &quot;#C7C8CF&quot;))</code></pre>
<p><img src="/blogs/bigmacindex_files/figure-html/cheapest_burger2-1.png" width="960" style="display: block; margin: auto;" /></p>
<p>Next we look in more detail at which countries are towards the lower level of the spectrum and which instead are the most expensive.</p>
<pre class="r"><code>#reducing the data to the cheapest 8 locations in July 2020
cheapest_july20 &lt;- bmindex_data %&gt;% 
  filter(date == c(&quot;2020-07-01&quot;)) %&gt;% 
  arrange(dollar_price) %&gt;% 
  head(8)

#graphing the price in US Dollars for the cheapest Big Macs in July 2020
p1 &lt;- cheapest_july20 %&gt;% 
  ggplot(aes(x = dollar_price, reorder(name, dollar_price))) +
  geom_col(fill = &quot;#DA291C&quot;) + 
  theme_few() +
  labs(
    title=&quot;South Africa has the cheapest Big Mac&quot;,
    subtitle=&quot;Price per country of a Big Mac in July 2020 &quot;,
    x=&quot;Price(US$)&quot;,
    y=&quot;Country&quot;) +
 scale_x_continuous(expand = c(0,0)) +
  theme(panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.text = element_text(color = &quot;#C7C8CF&quot;),
        axis.line = element_line(color = &quot;#C7C8CF&quot;))

#reducing the data to the most expensive 8 locations in July 2020
expensive_july20 &lt;- bmindex_data %&gt;% 
  filter(date == c(&quot;2020-07-01&quot;)) %&gt;% 
  arrange(desc(dollar_price)) %&gt;% 
  head(8)
  

#graphing the price for the most expensive Big Macs in July 2020
p2 &lt;- expensive_july20 %&gt;% 
  arrange(desc(dollar_price)) %&gt;%
  ggplot(aes(x = dollar_price, y = reorder(name,dollar_price))) +
  geom_col(fill = &quot;#FFC72C&quot;) + 
  labs(
    title=&quot;Swizerland has the most expensive Big Mac&quot;,
    subtitle=&quot;Price per country of a Big Mac in July 2020 &quot;,
    x=&quot;Price(US$)&quot;,
    y=&quot;Country&quot;) +
 scale_x_continuous(expand = c(0,0)) +
  theme(panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.text = element_text(color = &quot;#C7C8CF&quot;),
        axis.line = element_line(color = &quot;#C7C8CF&quot;))


grid.arrange(p1,p2, nrow = 1)</code></pre>
<p><img src="/blogs/bigmacindex_files/figure-html/most_expensive_burger-1.png" width="1152" style="display: block; margin: auto;" /></p>
<p>According to The Economist’s data, as of July 2020, South Africa was the country with the cheapest Big Mac (only $1.86) among the countries included in the study.
Vice versa, Swizerland, with almost 4 times the amount, sold the most expensive ($6.91).</p>
</div>
<div id="has-covid-impacted-the-price-for-big-mac" class="section level1">
<h1>Has Covid impacted the price for Big Mac?</h1>
<p>Next, I look into the percentage change in the price for a Big Mac between January and July 2020 the Big Mac has had in 2020. In fact, in light of China’s Covid-19 emergency, which unfolded in Europe and then worldwide in March 2020, I was curious to see what price fluctuations have taken place in 2020.
Interestingly, as reflected by the bar chart below, whilst the price has fluctuated, the price change has not been homogeneous across countries. Indeed, there is not a clear or similar pattern across countries, but rather, it increased in some whilst decreasing in others.</p>
<pre class="r"><code>#reducing the data to July 2020 and January observations only
covid_data &lt;- bmindex_data %&gt;% 
  filter(date == &quot;2020-07-01&quot; | date == &quot;2020-01-14&quot;) </code></pre>
<pre class="r"><code>test&lt;- covid_data %&gt;% 
  group_by(name) %&gt;%
  mutate(
    January= dplyr::first(dollar_price) , 
    July = dplyr::last(dollar_price)
  ) %&gt;%
  select(name,January,July) %&gt;%
  mutate(percentage_change = round(((July - January)/January)*100,2)) %&gt;% 
  slice(1:10) 
test &lt;- test[!duplicated(test$name),]
test</code></pre>
<pre><code>## # A tibble: 56 x 4
## # Groups:   name [56]
##    name       January  July percentage_change
##    &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;             &lt;dbl&gt;
##  1 Argentina     2.85  3.51             23.3 
##  2 Australia     4.45  4.58              2.86
##  3 Azerbaijan    2.33  2.32             -0.15
##  4 Bahrain       3.71  3.71             -0.01
##  5 Brazil        4.80  3.91            -18.6 
##  6 Britain       4.41  4.28             -3.01
##  7 Canada        5.18  5.08             -2.02
##  8 Chile         3.42  3.48              1.82
##  9 China         3.12  3.10             -0.78
## 10 Colombia      3.62  3.29             -9.11
## # … with 46 more rows</code></pre>
<pre class="r"><code>ggplot(test, aes(y = percentage_change, x = name, fill = name, label = name)) +
  geom_col() + 
  labs(title = &quot;Covid&#39;s impact on a Big Mac&#39;s price not homogeneous&quot;, subtitle = &quot;Percentage change in price between January and July 2020&quot;, x = &quot;Country&quot;, y = &quot;Percentage change&quot;) + 
  geom_text(size = 2, check_overlap = FALSE, color = &quot;#C7C8CF&quot;) +
  theme(legend.position = &quot;none&quot;, axis.text = element_blank(), axis.ticks = element_blank(), 
        panel.background = element_rect(fill = &quot;#2B304A&quot;, color = &quot;#2B304A&quot;), 
        panel.grid = element_blank(),
        plot.title = element_text(color = &quot;#C7C8CF&quot;, size = 10),
        plot.subtitle = element_text(color = &quot;#C7C8CF&quot;, size = 9),
        plot.background = element_rect(fill = &quot;#2B304A&quot;),
        axis.title = element_text(color = &quot;#C7C8CF&quot;), 
        axis.line = element_line(color = &quot;#C7C8CF&quot;))</code></pre>
<p><img src="/blogs/bigmacindex_files/figure-html/graph-1.png" width="960" style="display: block; margin: auto;" /></p>
</div>
